[mozci]
verbose = 1
data_sources=['treeherder', 'adr']
maxdepth = 5

[mozci.cache]
default = "file"
retention = 1000

[mozci.cache.stores]
file = { driver = "file", path = "mozci_tests_cache" }
redis = { driver = 'redis', host = 'localhost', port = 6379, db = 0 }

#[mozci.cache.stores.file]
#driver = "seeded-file"
#path = "mozci/cache"
#url = "https://s3-us-west-2.amazonaws.com/communitytc-bugbug/data/adr_cache.tar.zst"
#archive_relpath = "data/adr_cache"
#reseed_interval = 10080
